import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ShoppingBag, User, Gem, Gift, Wallet, ChevronRight, Activity, CircleDashed, ArrowUpCircle, Shield, LayoutGrid, Trophy, X, ListTodo, Settings, Bomb, Box, Package, ArrowLeft, Users, History, MessageCircle, ExternalLink, Copy, Check, Star } from 'lucide-react';
import defaultGiftsDb from './gifts_data.json';
import { Craft } from './components/Craft';
import { Upgrade } from './components/Upgrade';
import { Mines } from './components/Mines';
import { LiveFeed } from './components/LiveFeed';
import { PremiumImage } from './components/PremiumImage';
import { AdminPanel } from './components/AdminPanel';
import { Cases } from './components/Cases';
import { Leaderboard } from './components/Leaderboard';
import { Tasks } from './components/Tasks';
import { GramIcon } from './components/GramIcon';
import { TopUpModal } from './components/TopUpModal';
import { addTurnover } from './lib/stats';
import { useTelegramAuth } from './lib/useTelegramAuth';
import { useTranslation, i18n } from './lib/i18n';
import { CleanModelLottie } from './components/CleanModelLottie';
import { Inventory } from './components/Inventory';
import { fetchFragmentPrices } from './lib/api';
import { WelcomeScreen } from './components/WelcomeScreen';
